/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = string;
export interface ConversationView {
  'id' : bigint,
  'messages' : Array<Message>,
  'lastActivity' : Time,
  'createdAt' : Time,
  'conversations' : Array<Principal>,
}
export interface CreateMessageRequest {
  'recipient' : Principal,
  'messageType' : MessageType,
  'conversationId' : ConversationId,
}
export interface CreateUserRequest {
  'username' : string,
  'passwordHash' : string,
}
export type ExternalBlob = Uint8Array;
export type MediaType = { 'audio' : null } |
  { 'video' : null } |
  { 'document' : null } |
  { 'image' : null };
export interface Message {
  'recipient' : Principal,
  'sender' : Principal,
  'messageType' : MessageType,
  'timestamp' : Time,
}
export type MessageType = {
    'media' : {
      'blob' : ExternalBlob,
      'mediaType' : MediaType,
      'pinHash' : string,
    }
  } |
  { 'text' : string };
export type Time = bigint;
export interface UserProfile { 'username' : string, 'isActive' : boolean }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllActiveUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAllConversations' : ActorMethod<[], Array<ConversationView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[ConversationId], ConversationView>,
  'getMessagesInConversation' : ActorMethod<[ConversationId], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initiateConversation' : ActorMethod<[Principal], ConversationId>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[CreateUserRequest], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[CreateMessageRequest], Message>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'verifyMediaPin' : ActorMethod<
    [ExternalBlob, string, ConversationId],
    ExternalBlob
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];