/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'document' : IDL.Null,
  'image' : IDL.Null,
});
export const MessageType = IDL.Variant({
  'media' : IDL.Record({
    'blob' : ExternalBlob,
    'mediaType' : MediaType,
    'pinHash' : IDL.Text,
  }),
  'text' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'messageType' : MessageType,
  'timestamp' : Time,
});
export const ConversationView = IDL.Record({
  'id' : IDL.Nat,
  'messages' : IDL.Vec(Message),
  'lastActivity' : Time,
  'createdAt' : Time,
  'conversations' : IDL.Vec(IDL.Principal),
});
export const ConversationId = IDL.Text;
export const CreateUserRequest = IDL.Record({
  'username' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const CreateMessageRequest = IDL.Record({
  'recipient' : IDL.Principal,
  'messageType' : MessageType,
  'conversationId' : ConversationId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllActiveUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllConversations' : IDL.Func([], [IDL.Vec(ConversationView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([ConversationId], [ConversationView], ['query']),
  'getMessagesInConversation' : IDL.Func(
      [ConversationId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initiateConversation' : IDL.Func([IDL.Principal], [ConversationId], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([CreateUserRequest], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([CreateMessageRequest], [Message], []),
  'suspendUser' : IDL.Func([IDL.Principal], [], []),
  'verifyMediaPin' : IDL.Func(
      [ExternalBlob, IDL.Text, ConversationId],
      [ExternalBlob],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaType = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'document' : IDL.Null,
    'image' : IDL.Null,
  });
  const MessageType = IDL.Variant({
    'media' : IDL.Record({
      'blob' : ExternalBlob,
      'mediaType' : MediaType,
      'pinHash' : IDL.Text,
    }),
    'text' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'messageType' : MessageType,
    'timestamp' : Time,
  });
  const ConversationView = IDL.Record({
    'id' : IDL.Nat,
    'messages' : IDL.Vec(Message),
    'lastActivity' : Time,
    'createdAt' : Time,
    'conversations' : IDL.Vec(IDL.Principal),
  });
  const ConversationId = IDL.Text;
  const CreateUserRequest = IDL.Record({
    'username' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const CreateMessageRequest = IDL.Record({
    'recipient' : IDL.Principal,
    'messageType' : MessageType,
    'conversationId' : ConversationId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllActiveUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [ConversationId],
        [ConversationView],
        ['query'],
      ),
    'getMessagesInConversation' : IDL.Func(
        [ConversationId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initiateConversation' : IDL.Func([IDL.Principal], [ConversationId], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([CreateUserRequest], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([CreateMessageRequest], [Message], []),
    'suspendUser' : IDL.Func([IDL.Principal], [], []),
    'verifyMediaPin' : IDL.Func(
        [ExternalBlob, IDL.Text, ConversationId],
        [ExternalBlob],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };